{{- if .Values.lego.enabled }}
apiVersion: v1
metadata:
  name: {{ template "nginx-lego.fullname" . }}-lego
  labels: 
    configRevision : {{ .Values.configRevision}}
data:

  # modify this to specify your address
  lego.email: {{ .Values.lego.configmap.email | quote }}
  # configure letencrypt's production api
  lego.url: {{ .Values.lego.configmap.url | quote }}
kind: ConfigMap
{{- end }}
